export const API_URL = process.env.REACT_APP_SKYSCANNER_API_URL
export const GEOLOCATION_URL = process.env.REACT_APP_GEOLOCATION_URL
export const PLACES_URL = process.env.REACT_APP_SKYSCANNER_PLACES_URL
export const RAPIDAPI_HOST = process.env.REACT_APP_RAPIDAPI_HOST
export const RAPIDAPI_KEY = process.env.REACT_APP_RAPIDAPI_KEY
export const REFERENCE_URL = process.env.REACT_APP_SKYSCANNER_REFERENCE_URL
export const ROUTES_URL = process.env.REACT_APP_SKYSCANNER_ROUTES_URL
